base_url = "https://docs.medicamina.us"
title = "medicamina"
description = "Documentation for medicamina."
default_language = "en"
output_dir = "docs"
compile_sass = true
generate_feed = true
minify_html = true
taxonomies = [
  {name = "tags", feed = true },
  {name = "authors", feed = true},
  {name = "date", feed = true}
]
build_search_index = true
external_links_target_blank = true

[search]
include_title = true
include_description = true
include_content = true

[markdown]
highlight_code = true

[extra]
author = "medicamina"
github = "https://github.com/medicamina"
twitter = "https://x.com/medicamina_us"
ganalytics = ""  # Google Analytics code
is_netlify = false
language_code = "en-US"
theme_color = "#fff"
title_separator = "|"  # set as |, -, _, etc
title_addition = "documentation"
timeformat = "%Y-%m-%d %H:%M" # e.g. 2021-05-01 09:19:42
timezone = "UTC"
edit_page = false # Edit page on reposity or not
docs_repo = "https://github.com/medicamina/medicamina.github.io" # Edit page repo
repo_branch = "main"

## Math settings
# options: true, false. Enable math support globally,
# default: false. You can always enable math on a per page.
math = false
library = "katex"  # options: "katex", "mathjax". default is "katex".

## Open Graph + Twitter Cards
[extra.open]
enable = true
image = "doks.png"
twitter_site = "medicamina"
twitter_creator = "medicamina"
facebook_author = "medicamina"
facebook_publisher = "medicamina"
og_locale = "en_US"

## JSON-LD
[extra.schema]
type = "Organization"
logo = "logo.png"
twitter = "https://twitter.com/medicamina"
linked_in = "https://www.linkedin.com/company/medicamina"
github = "https://github.com/medicamina"
section = "blog" # see config.extra.main~url
site_links_search_box = false

[[extra.menu.social]]
name = "Twitter"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>'
url = "https://twitter.com/medicamina"
weight = 10

[[extra.menu.social]]
name = "GitHub"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
url = "https://github.com/medicamina"
post = "v0.1.0"
weight = 20

# Footer contents
[extra.footer]
info = 'Blog powered by <a href="https://www.getzola.org/">Zola</a>, <a href="https://github.com/aaranxu/adidoks">AdiDoks</a> and <a href="https://pages.github.com">GitHub Pages</a>'

[[extra.footer.nav]]
name = "Privacy Policy"
url = "/privacy-policy/"
weight = 10

[[extra.footer.nav]]
name = "License Agreement"
url = "/license/"
weight = 20

# [[extra.footer.nav]]
# name = "Contributors"
# url = "/contributors/"
# weight = 30

# [[extra.footer.nav]]
# name = "Contact"
# url = "/contact/"
# weight = 40
